import type { AreaComun, Reserva } from "@/types";

export const areasComunes: AreaComun[] = [
  { id: "a1", nombre: "Parrilla", descripcion: "Espacio al aire libre con parrilla, mesa y sillas. Ideal para reuniones familiares y asados.", costoPorHora: 50, modoReserva: "Por hora", capacidadMaxima: 15, requiereGarantia: true, montoGarantia: 150, reglasUso: "No dejar basura. Limpiar parrilla al terminar. Respetar horario de silencio desde las 10pm.", estado: "Activa", reservasActivas: 3 },
  { id: "a2", nombre: "Salón de Eventos", descripcion: "Salón climatizado con cocina equipada, baños y equipo de sonido. Capacidad para 50 personas.", costoPorHora: 120, modoReserva: "Medio día", capacidadMaxima: 50, requiereGarantia: true, montoGarantia: 500, reglasUso: "Reserva con mínimo 48h de anticipación. Depósito de garantía reembolsable. No exceder la capacidad máxima.", estado: "Activa", reservasActivas: 1 },
  { id: "a3", nombre: "Piscina", descripcion: "Piscina temperada con vestidores y duchas. Área de reposo con sombrillas.", costoPorHora: 0, modoReserva: "Medio día", capacidadMaxima: 30, requiereGarantia: false, montoGarantia: 0, reglasUso: "Uso obligatorio de traje de baño. Niños acompañados de adulto. No ingresar con alimentos.", estado: "Activa", reservasActivas: 6 },
  { id: "a4", nombre: "Gimnasio", descripcion: "Gimnasio equipado con máquinas cardiovasculares y pesas. Acceso 24/7.", costoPorHora: 0, modoReserva: "Por hora", capacidadMaxima: 10, requiereGarantia: false, montoGarantia: 0, reglasUso: "Traer toalla personal. Limpiar máquinas después de usar. Máximo 1 hora en hora punta.", estado: "Activa", reservasActivas: 0 },
  { id: "a5", nombre: "Sala de Reuniones", descripcion: "Sala equipada con proyector, pizarra y videoconferencia. Capacidad para 12 personas.", costoPorHora: 35, modoReserva: "Por hora", capacidadMaxima: 12, requiereGarantia: false, montoGarantia: 0, reglasUso: "Reserva máximo 4 horas. Dejar sala ordenada. Apagar equipos al salir.", estado: "Inactiva", reservasActivas: 0 },
  { id: "a6", nombre: "Terraza", descripcion: "Terraza en el último piso con vista panorámica. Área de descanso con jardín.", costoPorHora: 0, modoReserva: "Todo el día", capacidadMaxima: 20, requiereGarantia: true, montoGarantia: 100, reglasUso: "No se permite música amplificada. Respetar zonas verdes. No mascotas.", estado: "Activa", reservasActivas: 2 },
];

export const reservas: Reserva[] = [
  { id: "rv1", areaComunId: "a1", areaComunNombre: "Parrilla", residenteId: "r1", residenteNombre: "Luis García", inmuebleId: "i1", inmuebleLabel: "Dpto 101", fecha: "2026-05-10", horaInicio: "18:00", horaFin: "22:00", costoTotal: 200, estado: "Confirmada", observaciones: "Familiar — 10 personas" },
  { id: "rv2", areaComunId: "a2", areaComunNombre: "Salón de Eventos", residenteId: "r3", residenteNombre: "Jorge Mendoza", inmuebleId: "i3", inmuebleLabel: "Dpto 201", fecha: "2026-05-12", horaInicio: "14:00", horaFin: "20:00", costoTotal: 360, estado: "Confirmada", observaciones: "Cumpleaños 15 — 40 invitados" },
  { id: "rv3", areaComunId: "a3", areaComunNombre: "Piscina", residenteId: "r8", residenteNombre: "Diana López", inmuebleId: "i8", inmuebleLabel: "Dpto 102", fecha: "2026-05-15", horaInicio: "10:00", horaFin: "14:00", costoTotal: 0, estado: "Confirmada", observaciones: "Tarde familiar" },
  { id: "rv4", areaComunId: "a1", areaComunNombre: "Parrilla", residenteId: "r9", residenteNombre: "Roberto Díaz", inmuebleId: "i9", inmuebleLabel: "Dpto 501", fecha: "2026-05-17", horaInicio: "17:00", horaFin: "21:00", costoTotal: 200, estado: "Solicitada", observaciones: "Cena con amigos" },
  { id: "rv5", areaComunId: "a6", areaComunNombre: "Terraza", residenteId: "r5", residenteNombre: "Ana Quispe", inmuebleId: "i5", inmuebleLabel: "Dpto 301", fecha: "2026-05-20", horaInicio: "08:00", horaFin: "18:00", costoTotal: 0, estado: "Confirmada", observaciones: "Evento de yoga matutino" },
  { id: "rv6", areaComunId: "a3", areaComunNombre: "Piscina", residenteId: "r11", residenteNombre: "Martín Castro", inmuebleId: "i12", inmuebleLabel: "Dpto 301 Las Flores", fecha: "2026-05-08", horaInicio: "14:00", horaFin: "18:00", costoTotal: 0, estado: "Realizada", observaciones: "" },
  { id: "rv7", areaComunId: "a1", areaComunNombre: "Parrilla", residenteId: "r7", residenteNombre: "Carlos Ruiz", inmuebleId: "i7", inmuebleLabel: "Dpto 101 Bloque B", fecha: "2026-05-18", horaInicio: "12:00", horaFin: "16:00", costoTotal: 200, estado: "Pagada", observaciones: "Almuerzo de trabajo" },
  { id: "rv8", areaComunId: "a4", areaComunNombre: "Gimnasio", residenteId: "r2", residenteNombre: "María Torres", inmuebleId: "i2", inmuebleLabel: "Dpto 102", fecha: "2026-04-25", horaInicio: "07:00", horaFin: "08:00", costoTotal: 0, estado: "Cancelada", observaciones: "Cancelado por mantenimiento" },
];
