import type { Persona, MiembroDirectiva, Multa } from "@/types";

export const residentes: Persona[] = [
  {
    id: "r1",
    tipo: "Natural",
    documento: "12345678",
    nombres: "Luis",
    apellidos: "García Fernández",
    genero: "M",
    fechaNacimiento: "1985-03-15",
    contactos: [
      { tipo: "email", valor: "luis.garcia@email.com" },
      { tipo: "telefono", valor: "+51 987654321" },
    ],
    vinculaciones: [{ inmuebleId: "i1", inmuebleLabel: "Dpto 101 - Torre Sol", rol: "Propietario" }],
    saldo: 0,
    activo: true,
  },
  {
    id: "r2",
    tipo: "Natural",
    documento: "87654321",
    nombres: "María",
    apellidos: "Torres Quispe",
    genero: "F",
    fechaNacimiento: "1990-07-22",
    contactos: [
      { tipo: "email", valor: "maria.torres@email.com" },
      { tipo: "telefono", valor: "+51 912345678" },
    ],
    vinculaciones: [{ inmuebleId: "i2", inmuebleLabel: "Dpto 102 - Torre Sol", rol: "Propietario" }],
    saldo: -450,
    activo: true,
  },
  {
    id: "r3",
    tipo: "Natural",
    documento: "45678901",
    nombres: "Jorge",
    apellidos: "Mendoza Ríos",
    genero: "M",
    fechaNacimiento: "1978-11-30",
    contactos: [
      { tipo: "email", valor: "jorge.mendoza@email.com" },
      { tipo: "telefono", valor: "+51 934567890" },
    ],
    vinculaciones: [{ inmuebleId: "i3", inmuebleLabel: "Dpto 201 - Torre Sol", rol: "Propietario" }],
    saldo: 0,
    activo: true,
  },
  {
    id: "r4",
    tipo: "Jurídica",
    documento: "20123456789",
    nombres: "",
    apellidos: "",
    razonSocial: "Inversiones del Sur SAC",
    contactos: [
      { tipo: "email", valor: "contacto@inversionesdelsur.pe" },
      { tipo: "telefono", valor: "+51 1 2345678" },
    ],
    vinculaciones: [{ inmuebleId: "i4", inmuebleLabel: "Dpto 202 - Torre Sol", rol: "Propietario" }],
    saldo: 0,
    activo: true,
  },
  {
    id: "r5",
    tipo: "Natural",
    documento: "23456789",
    nombres: "Ana",
    apellidos: "Quispe Huamán",
    genero: "F",
    fechaNacimiento: "1992-05-08",
    contactos: [
      { tipo: "email", valor: "ana.quispe@email.com" },
      { tipo: "telefono", valor: "+51 945678901" },
    ],
    vinculaciones: [{ inmuebleId: "i5", inmuebleLabel: "Dpto 301 - Torre Sol", rol: "Inquilino" }],
    saldo: -120,
    activo: true,
  },
  {
    id: "r6",
    tipo: "Natural",
    documento: "34567890",
    nombres: "Pedro",
    apellidos: "Sánchez Díaz",
    genero: "M",
    fechaNacimiento: "1982-09-14",
    contactos: [
      { tipo: "email", valor: "pedro.sanchez@email.com" },
      { tipo: "telefono", valor: "+51 956789012" },
    ],
    vinculaciones: [{ inmuebleId: "i6", inmuebleLabel: "Dpto 302 - Torre Sol", rol: "Propietario" }],
    saldo: -1250,
    activo: true,
  },
  {
    id: "r7",
    tipo: "Natural",
    documento: "56789012",
    nombres: "Carlos",
    apellidos: "Ruiz Palomino",
    genero: "M",
    fechaNacimiento: "1975-01-20",
    contactos: [
      { tipo: "email", valor: "carlos.ruiz@email.com" },
      { tipo: "telefono", valor: "+51 967890123" },
    ],
    vinculaciones: [{ inmuebleId: "i7", inmuebleLabel: "Dpto 101 - Bloque B", rol: "Propietario" }],
    saldo: 0,
    activo: true,
  },
  {
    id: "r8",
    tipo: "Natural",
    documento: "67890123",
    nombres: "Diana",
    apellidos: "López Vega",
    genero: "F",
    fechaNacimiento: "1988-12-03",
    contactos: [
      { tipo: "email", valor: "diana.lopez@email.com" },
      { tipo: "telefono", valor: "+51 978901234" },
    ],
    vinculaciones: [{ inmuebleId: "i8", inmuebleLabel: "Dpto 102 - Bloque B", rol: "Propietario" }],
    saldo: -200,
    activo: true,
  },
  {
    id: "r9",
    tipo: "Natural",
    documento: "78901234",
    nombres: "Roberto",
    apellidos: "Díaz Castro",
    genero: "M",
    fechaNacimiento: "1970-06-18",
    contactos: [
      { tipo: "email", valor: "roberto.diaz@email.com" },
      { tipo: "telefono", valor: "+51 989012345" },
    ],
    vinculaciones: [{ inmuebleId: "i9", inmuebleLabel: "Dpto 501 - Bloque C", rol: "Propietario" }],
    saldo: 0,
    activo: true,
  },
  {
    id: "r10",
    tipo: "Natural",
    documento: "89012345",
    nombres: "Sofía",
    apellidos: "Vargas Nina",
    genero: "F",
    fechaNacimiento: "1995-04-11",
    contactos: [
      { tipo: "email", valor: "sofia.vargas@email.com" },
      { tipo: "telefono", valor: "+51 990123456" },
    ],
    vinculaciones: [{ inmuebleId: "i10", inmuebleLabel: "Dpto 101 - Las Flores", rol: "Inquilino" }],
    saldo: 0,
    activo: true,
  },
  {
    id: "r11",
    tipo: "Natural",
    documento: "90123456",
    nombres: "Martín",
    apellidos: "Castro Luque",
    genero: "M",
    fechaNacimiento: "1983-08-27",
    contactos: [
      { tipo: "email", valor: "martin.castro@email.com" },
      { tipo: "telefono", valor: "+51 901234567" },
    ],
    vinculaciones: [{ inmuebleId: "i12", inmuebleLabel: "Dpto 301 - Las Flores B", rol: "Familiar" }],
    saldo: -80,
    activo: true,
  },
  {
    id: "r12",
    tipo: "Natural",
    documento: "01234567",
    nombres: "Carmen",
    apellidos: "Medina Soto",
    genero: "F",
    fechaNacimiento: "1991-02-14",
    contactos: [
      { tipo: "email", valor: "carmen.medina@email.com" },
      { tipo: "telefono", valor: "+51 912345670" },
    ],
    vinculaciones: [{ inmuebleId: "i11", inmuebleLabel: "Dpto 202 - Las Flores", rol: "Propietario" }],
    saldo: 0,
    activo: false,
  },
];

export const directiva: MiembroDirectiva[] = [
  {
    id: "d1",
    residenteId: "r1",
    residenteNombre: "Luis García Fernández",
    cargo: "Presidente",
    fechaInicio: "2026-01-01",
    fechaFin: "2027-12-31",
    estado: "Activo",
  },
  {
    id: "d2",
    residenteId: "r3",
    residenteNombre: "Jorge Mendoza Ríos",
    cargo: "Vicepresidente",
    fechaInicio: "2026-01-01",
    fechaFin: "2027-12-31",
    estado: "Activo",
  },
  {
    id: "d3",
    residenteId: "r7",
    residenteNombre: "Carlos Ruiz Palomino",
    cargo: "Tesorero",
    fechaInicio: "2026-01-01",
    fechaFin: "2027-12-31",
    estado: "Activo",
  },
  {
    id: "d4",
    residenteId: "r2",
    residenteNombre: "María Torres Quispe",
    cargo: "Secretario",
    fechaInicio: "2026-01-01",
    fechaFin: "2027-12-31",
    estado: "Activo",
  },
  {
    id: "d5",
    residenteId: "r9",
    residenteNombre: "Roberto Díaz Castro",
    cargo: "Vocal",
    fechaInicio: "2026-01-01",
    fechaFin: "2027-12-31",
    estado: "Activo",
  },
  {
    id: "d6",
    residenteId: "r6",
    residenteNombre: "Pedro Sánchez Díaz",
    cargo: "Presidente",
    fechaInicio: "2024-01-01",
    fechaFin: "2025-12-31",
    estado: "Histórico",
  },
];

export const multas: Multa[] = [
  {
    id: "m1",
    residenteId: "r5",
    residenteNombre: "Ana Quispe Huamán",
    inmuebleId: "i5",
    inmuebleLabel: "Dpto 301 - Torre Sol",
    motivo: "ruido",
    descripcion: "Música a alto volumen pasadas las 11pm. Reincidencia.",
    monto: 150,
    fechaEmision: "2026-04-15",
    fechaVencimiento: "2026-05-15",
    estado: "Pendiente",
    aplicadaPor: "Administración",
  },
  {
    id: "m2",
    residenteId: "r8",
    residenteNombre: "Diana López Vega",
    inmuebleId: "i8",
    inmuebleLabel: "Dpto 102 - Bloque B",
    motivo: "mascota",
    descripcion: "Perro sin correa en áreas comunes. Sin bozal.",
    monto: 200,
    fechaEmision: "2026-04-10",
    fechaVencimiento: "2026-05-10",
    estado: "Vencida",
    aplicadaPor: "Directiva",
  },
  {
    id: "m3",
    residenteId: "r2",
    residenteNombre: "María Torres Quispe",
    inmuebleId: "i2",
    inmuebleLabel: "Dpto 102 - Torre Sol",
    motivo: "basura",
    descripcion: "Residuos acumulados en el pasillo común.",
    monto: 100,
    fechaEmision: "2026-03-20",
    fechaVencimiento: "2026-04-20",
    estado: "Pagada",
    aplicadaPor: "Administración",
  },
  {
    id: "m4",
    residenteId: "r11",
    residenteNombre: "Martín Castro Luque",
    inmuebleId: "i12",
    inmuebleLabel: "Dpto 301 - Las Flores B",
    motivo: "estacionamiento",
    descripcion: "Vehículo estacionado en espacio asignado a otro residente.",
    monto: 120,
    fechaEmision: "2026-04-28",
    fechaVencimiento: "2026-05-28",
    estado: "Pendiente",
    aplicadaPor: "Administración",
  },
  {
    id: "m5",
    residenteId: "r1",
    residenteNombre: "Luis García Fernández",
    inmuebleId: "i1",
    inmuebleLabel: "Dpto 101 - Torre Sol",
    motivo: "area_comun",
    descripcion: "Daños en la pintura del salón de eventos tras reunión.",
    monto: 350,
    fechaEmision: "2026-02-05",
    fechaVencimiento: "2026-03-05",
    estado: "Pagada",
    aplicadaPor: "Directiva",
  },
  {
    id: "m6",
    residenteId: "r6",
    residenteNombre: "Pedro Sánchez Díaz",
    inmuebleId: "i6",
    inmuebleLabel: "Dpto 302 - Torre Sol",
    motivo: "ruido",
    descripcion: "Fiesta hasta las 3am con quejas de 4 vecinos.",
    monto: 250,
    fechaEmision: "2026-05-01",
    fechaVencimiento: "2026-06-01",
    estado: "Pendiente",
    aplicadaPor: "Administración",
  },
  {
    id: "m7",
    residenteId: "r10",
    residenteNombre: "Sofía Vargas Nina",
    inmuebleId: "i10",
    inmuebleLabel: "Dpto 101 - Las Flores",
    motivo: "otro",
    descripcion: "Modificación no autorizada de instalaciones eléctricas.",
    monto: 500,
    fechaEmision: "2026-04-01",
    fechaVencimiento: "2026-05-01",
    estado: "Anulada",
    aplicadaPor: "Administración",
  },
];
