import type { CargoServicio, CargoTotalResumen, CuotaMantenimiento } from "@/types";

export const cargosServicio: CargoServicio[] = [
  { id: "cs1", inmuebleId: "i1", inmuebleLabel: "Dpto 101 - Torre Sol", servicioId: "s1", servicioNombre: "Agua", periodo: "2026-04", lecturaAnterior: 1250, lecturaActual: 1280, consumo: 30, tarifa: 3.5, monto: 105, estado: "Pagado", registradoPor: "Carlos Ruiz" },
  { id: "cs2", inmuebleId: "i2", inmuebleLabel: "Dpto 102 - Torre Sol", servicioId: "s1", servicioNombre: "Agua", periodo: "2026-04", lecturaAnterior: 980, lecturaActual: 1015, consumo: 35, tarifa: 3.5, monto: 122.5, estado: "Pendiente", registradoPor: "Carlos Ruiz" },
  { id: "cs3", inmuebleId: "i3", inmuebleLabel: "Dpto 201 - Torre Sol", servicioId: "s1", servicioNombre: "Agua", periodo: "2026-04", lecturaAnterior: 1100, lecturaActual: 1125, consumo: 25, tarifa: 3.5, monto: 87.5, estado: "Pagado", registradoPor: "Carlos Ruiz" },
  { id: "cs4", inmuebleId: "i1", inmuebleLabel: "Dpto 101 - Torre Sol", servicioId: "s2", servicioNombre: "Luz Áreas Comunes", periodo: "2026-04", lecturaAnterior: 0, lecturaActual: 0, consumo: 0, tarifa: 0.85, monto: 42.5, estado: "Pendiente", registradoPor: "Carlos Ruiz" },
  { id: "cs5", inmuebleId: "i2", inmuebleLabel: "Dpto 102 - Torre Sol", servicioId: "s2", servicioNombre: "Luz Áreas Comunes", periodo: "2026-04", lecturaAnterior: 0, lecturaActual: 0, consumo: 0, tarifa: 0.85, monto: 42.5, estado: "Pendiente", registradoPor: "Carlos Ruiz" },
  { id: "cs6", inmuebleId: "i5", inmuebleLabel: "Dpto 301 - Torre Sol", servicioId: "s1", servicioNombre: "Agua", periodo: "2026-04", lecturaAnterior: 850, lecturaActual: 890, consumo: 40, tarifa: 3.5, monto: 140, estado: "Pendiente", registradoPor: "Carlos Ruiz" },
];

export const cargosTotales: CargoTotalResumen[] = [
  {
    inmuebleId: "i1",
    inmuebleLabel: "Dpto 101 - Torre Sol A",
    residenteNombre: "Luis García Fernández",
    cargos: [
      { tipo: "Mantenimiento", descripcion: "Cuota ordinaria - Abr 2026", monto: 350, estado: "Pagado", fechaEmision: "2026-04-01" },
      { tipo: "Servicio", descripcion: "Agua - Abr 2026", monto: 105, estado: "Pagado", fechaEmision: "2026-04-01" },
      { tipo: "Servicio", descripcion: "Luz Áreas - Abr 2026", monto: 42.5, estado: "Pendiente", fechaEmision: "2026-04-01" },
      { tipo: "Mantenimiento", descripcion: "Cuota ordinaria - May 2026", monto: 350, estado: "Pendiente", fechaEmision: "2026-05-01" },
    ],
    totalCargos: 847.5,
    totalPagado: 455,
    saldoPendiente: 392.5,
    interesMora: 0,
  },
  {
    inmuebleId: "i2",
    inmuebleLabel: "Dpto 102 - Torre Sol A",
    residenteNombre: "María Torres Quispe",
    cargos: [
      { tipo: "Mantenimiento", descripcion: "Cuota ordinaria - Abr 2026", monto: 380, estado: "Vencido", fechaEmision: "2026-04-01" },
      { tipo: "Servicio", descripcion: "Agua - Abr 2026", monto: 122.5, estado: "Vencido", fechaEmision: "2026-04-01" },
      { tipo: "Servicio", descripcion: "Luz Áreas - Abr 2026", monto: 42.5, estado: "Vencido", fechaEmision: "2026-04-01" },
      { tipo: "Multa", descripcion: "Residuos en pasillo", monto: 100, estado: "Pagado", fechaEmision: "2026-03-20" },
      { tipo: "Mantenimiento", descripcion: "Cuota ordinaria - May 2026", monto: 380, estado: "Pendiente", fechaEmision: "2026-05-01" },
    ],
    totalCargos: 1025,
    totalPagado: 100,
    saldoPendiente: 925,
    interesMora: 45.25,
  },
  {
    inmuebleId: "i6",
    inmuebleLabel: "Dpto 302 - Torre Sol C",
    residenteNombre: "Pedro Sánchez Díaz",
    cargos: [
      { tipo: "Mantenimiento", descripcion: "Cuota ordinaria - Mar 2026", monto: 320, estado: "Vencido", fechaEmision: "2026-03-01" },
      { tipo: "Mantenimiento", descripcion: "Cuota ordinaria - Abr 2026", monto: 320, estado: "Vencido", fechaEmision: "2026-04-01" },
      { tipo: "Servicio", descripcion: "Agua - Abr 2026", monto: 140, estado: "Vencido", fechaEmision: "2026-04-01" },
      { tipo: "Multa", descripcion: "Ruido - Fiesta hasta 3am", monto: 250, estado: "Vencido", fechaEmision: "2026-05-01" },
      { tipo: "Mantenimiento", descripcion: "Cuota ordinaria - May 2026", monto: 320, estado: "Pendiente", fechaEmision: "2026-05-01" },
    ],
    totalCargos: 1350,
    totalPagado: 0,
    saldoPendiente: 1350,
    interesMora: 120.80,
  },
  {
    inmuebleId: "i7",
    inmuebleLabel: "Dpto 101 - Bloque B",
    residenteNombre: "Carlos Ruiz Palomino",
    cargos: [
      { tipo: "Mantenimiento", descripcion: "Cuota ordinaria - Abr 2026", monto: 400, estado: "Pagado", fechaEmision: "2026-04-01" },
      { tipo: "Mantenimiento", descripcion: "Cuota ordinaria - May 2026", monto: 400, estado: "Pendiente", fechaEmision: "2026-05-01" },
    ],
    totalCargos: 800,
    totalPagado: 400,
    saldoPendiente: 400,
    interesMora: 0,
  },
];

export const cuotasMantenimiento: CuotaMantenimiento[] = [
  {
    id: "c1",
    periodo: "2026-05",
    tipo: "Ordinaria",
    montoBase: 350,
    criterio: "Igual",
    fechaEmision: "2026-05-01",
    fechaVencimiento: "2026-05-15",
    moraDiaria: 0.05,
    estado: "Emitida",
    inmueblesAplicados: 12,
    totalEmitido: 4200,
    totalCobrado: 3150,
  },
  {
    id: "c2",
    periodo: "2026-04",
    tipo: "Ordinaria",
    montoBase: 350,
    criterio: "Igual",
    fechaEmision: "2026-04-01",
    fechaVencimiento: "2026-04-15",
    moraDiaria: 0.05,
    estado: "Vencida",
    inmueblesAplicados: 12,
    totalEmitido: 4200,
    totalCobrado: 3850,
  },
  {
    id: "c3",
    periodo: "2026-03",
    tipo: "Ordinaria",
    montoBase: 350,
    criterio: "Igual",
    fechaEmision: "2026-03-01",
    fechaVencimiento: "2026-03-15",
    moraDiaria: 0.05,
    estado: "Cerrada",
    inmueblesAplicados: 12,
    totalEmitido: 4200,
    totalCobrado: 4200,
  },
  {
    id: "c4",
    periodo: "2026-06",
    tipo: "Extraordinaria",
    montoBase: 500,
    criterio: "Alícuota",
    fechaEmision: "2026-06-01",
    fechaVencimiento: "2026-06-20",
    moraDiaria: 0.05,
    estado: "Borrador",
    inmueblesAplicados: 0,
    totalEmitido: 0,
    totalCobrado: 0,
  },
  {
    id: "c5",
    periodo: "2026-02",
    tipo: "Ordinaria",
    montoBase: 350,
    criterio: "Igual",
    fechaEmision: "2026-02-01",
    fechaVencimiento: "2026-02-15",
    moraDiaria: 0.05,
    estado: "Cerrada",
    inmueblesAplicados: 12,
    totalEmitido: 4200,
    totalCobrado: 4200,
  },
];
